[package]
name = "oxide-shield"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
dashmap = "6.1.0"
http-body-util = "0.1.3"
hyper = { version = "1.9.0", features = ["http1", "server", "client"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "net", "io-util", "test-util"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1